# CI de nível 01 - Disparo manual a partir de 1 clique

# nome do nosso 'pipeline'

name: 'Execução Manual'

# regras de disparo (gatilhos/triggers)
# gatilho de execução manual = workflow_dispatch

on:
  workflow_dispatch:

# trabalhos/tarefas dentro do pipeline = jobs
jobs:
  e2e-tests:

    #Maquina que o job vai executar
    runs-on: ubuntu-latest  
    
    # passos do script de build
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: latest

      # instalação do yarn
      - name: Instalando yarn
        run: npm install -g yarn


      # instalação das depedências
      - name: Instalando depedências
        run: yarn

      # instalação do navegadores Playwright
      - name: Instalando Playwright
        run: yarn playwright install

      # executar os testes e2e
      - name: Executando Testes E2E
        run: yarn run e2e
        continue-on-error: true

      # Relatório visual direto no GitHub
      - name: Exibir Relatório JUnit no GitHub
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Relatório de Testes Playwright
          path: results.xml
          reporter: java-junit

      # Relatório HTML como artefato
      - name: Salvar Relatório HTML Playwright
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: playwright-report/
        

