# CI de nível 01 - Disparo manual a partir de 1 clique

# nome do nosso 'pipeline'

name: 'Execução Manual'

# regras de disparo (gatilhos/triggers)
# gatilho de execução manual = workflow_dispatch

on:
  workflow_dispatch:

# trabalhos/tarefas dentro do pipeline = jobs
jobs:
  e2e-tests:

    #Maquina que o job vai executar
    runs-on: ubuntu-latest  
    
    # passos do script de build
    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: latest

      # instalação do yarn
      - name: Instalando yarn
        run: npm install -g yarn


      # instalação das depedências
      - name: Instalando depedências
        run: yarn

      # instalação do navegadores Playwright
      - name: Instalando Playwright
        run: yarn playwright install

      # executar os testes e2e
      - name: Executando Testes E2E
        run: yarn run e2e

