# CI de nível 04 - Disparo dos testes dentro do pipeline

name: 'Execução Integrada'

on:
  workflow_dispatch:

jobs:
  inspecao:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Checando padronizado o código
        run: yarn Lint

  unidade:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn

      - name: Executando testes de unidades
        run: yarn test

  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      # clone do projeto
      - uses: actions/checkout@v4

      # instalação do node
      - uses: actions/setup-node@v4
        with:
          node-version: latest

      # instalação do yarn
      - name: Instalando yarn
        run: npm install -g yarn

      # instalação das depedências
      - name: Instalando depedências
        run: yarn

      # instalação do navegadores Playwright
      - name: Instalando Playwright
        run: yarn playwright install

      # executar os testes e2e
      - name: Executando Testes E2E
        run: yarn run e2e

      # sobe arquivos relevantes para que eu possa fazer o download depois
      # Condicional a nível Step
      # Eu quero que baixe este relatório exceto se for cancelado
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: report
          path: ./playwright-report

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Simulação do Deploy
        run: echo "simulando o deploy com sucesso"
